name = "adrastea-r2-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGINS = "http://localhost:5173,http://localhost:6100,http://100.121.7.83:5173,http://100.121.7.83:6100,https://jupiter-systems.pages.dev,https://jupiter-systems.vercel.app"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "adrastea-assets"

[[d1_databases]]
binding = "DB"
database_name = "adrastea-db"
database_id = "3816e6dc-5093-47da-8811-ea36ea6257c2"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "96731d59658e45bf811597ed40c56f39"
