name: Keep Server Alive

on:
  schedule:
    # 10分ごとに実行（UTC時間）
    - cron: '*/10 * * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping server
        run: |
          curl -s https://trpg-pdf2md-api.onrender.com/ || true
          echo "Pinged server at $(date)"